# Generated by Django 5.1.1 on 2024-10-05 10:08

import autoslug.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100)),
                ('product_img', models.ImageField(upload_to='app_images/')),
                ('product_price', tinymce.models.HTMLField()),
                ('product_quantity', tinymce.models.HTMLField()),
                ('product_slug', autoslug.fields.AutoSlugField(blank=True, default=None, editable=False, null=True, populate_from='product_title', unique=True)),
            ],
        ),
    ]
