# Generated by Django 5.1.1 on 2024-10-07 06:47

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=tinymce.models.HTMLField(),
        ),
    ]
